CPP_FLAG := -std=c++11

03 : RepeatingNumInArr_03.cpp
	g++ $(CPP_FLAG) RepeatingNumInArr_03.cpp -o run

68_2 : LowestCommonAncestor_68_II.cpp ../utils/ser_de_binary_tree.o
	g++ $(CPP_FLAG) LowestCommonAncestor_68_II.cpp ../utils/ser_de_binary_tree.o -o run
